### PR TITLE
RoasterFormModelSourceGeneratorTest & related changes

### PR DESCRIPTION
**Pull request by jsoltes**
Unit test for RoasterFormModelSourceGenerator class, small refactoring and a fix of situation where empty dataHolders set is passed to the generator and two constructors are generated.

### CODE REVIEW

**Comment by jsoltes** [comment]
The build seems to be failing due to reasons unrelated to the change I made (it fails also with the previous version). It might be due to the previous commit (Fixes after IP BOM 7.0.0.CR4 upgrade (#31)) or changes made somewhere else in the product. @paulovmr could you please look at the LiveSparkEntryPointTest - why it fails?

**Comment by paulovmr** [comment]
@jsoltes Hi, LiveSparkEntryPointTest was broke by this line removal: https://github.com/droolsjbpm/livespark/commit/c4c29a92ee66cd34e13e1b8c464d55fde09dacf8#diff-058918d9f053df0c3ad85a13037dae30L99

I'll send a PR to fix the test.

**Comment by paulovmr** [comment]
@jsoltes Here is the PR: https://github.com/droolsjbpm/livespark/pull/33

**Comment by csadilek** [comment]
jenkins retest this.

**Comment by jsoltes** [comment]
As in PR #33, the failing test is caused by: https://issues.jboss.org/browse/UF-335

**Comment by csadilek** [comment]
+1, thanks for the test @jsoltes.

**Pull request merged**
