### PR TITLE
GUVNOR-2502: Consolidate client-side bootstrap logic in various workbench implementations

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
To merge together with:

https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/202
https://github.com/uberfire/uberfire/pull/372
https://github.com/droolsjbpm/kie-wb-common/pull/360
https://github.com/droolsjbpm/jbpm-form-modeler/pull/50
https://github.com/droolsjbpm/drools-wb/pull/176
https://github.com/droolsjbpm/jbpm-designer/pull/256
https://github.com/droolsjbpm/jbpm-console-ng/pull/421
https://github.com/droolsjbpm/optaplanner-wb/pull/69
https://github.com/droolsjbpm/livespark/pull/22
https://github.com/droolsjbpm/kie-wb-distributions/pull/285

**Comment by paulovmr** [comment]
jenkins please retest this

**Comment by mbarkley** [comment]
Hi @paulovmr ,

The LiveSpark PR build currently isn't configured to build dependent projects for related PRs ( @psiroky  is working on this).

I can review this PR and run the tests locally while doing so.

**Comment by paulovmr** [comment]
Hi @mbarkley , thanks, I was going to ask @psiroky exactly that :)

**Comment by psiroky** [comment]
Hello @mbarkley, @paulovmr. Will we ever add livespark in to our buildchain? or will livespark be different project with different version? The current situation is bit weird -- it needs other SNAPSHOT deps, but it in fact not part of our build chain.

**Comment by mbarkley** [comment]
Hi @paulovmr 

Locally I get a test failure with this error:
`org.guvnor.common.services.project.service.GAVAlreadyExistsException: Requested GAV already exists. Please check 'repositories' collection.`

I'm about to sign-off but I can help you look into this tomorrow. Until then you can try to reproduce this on your machine by doing a `mvn clean install` in the livespark root (after building droolsjbpm-build-bootstrap and uberfire).

**Comment by mbarkley** [comment]
@psiroky , what we know right now is that LiveSpark will continue being actively developed, but it will be renamed in the next few months (which I guess will require a new repository). @csadilek might have more concrete information after this weeks meetings.

**Comment by manstis** [comment]
IDK LiveSpark but guvnor's M2 Repository checks whether a GAV already
exists on an install or deploy. There are also checks in kie-wb-common when
creating a new Project. If the LiveSpark tests don't clear down any M2 they
use this error can result. The check for duplicate GAV can be disabled with
a System Property.

**Comment by mbarkley** [comment]
Thanks for the tip @manstis 

@paulovmr I ran the tests again after clearing some artifacts from my local repo and sure enough everything passes.

+1

**Comment by paulovmr** [comment]
Thanks for the review, @mbarkley . Not related to this PR, but I am having problems building livespark. I tried cloning livespark master branch, and running mvn clean install -U, but some failures happen on the BuildAndDeploymentTest execution: https://gist.github.com/paulovmr/9df6674eb1bf6b5e512ca8ddee6f6587

Do you know if I have to install and/or configure something to make this work?

**Comment by mbarkley** [comment]
@paulovmr The only gotcha with the LiveSpark integration tests is that you need to install the livespark-webapp first because the BuildAndDeploymentTest tests that war file, which it resolves with maven, but since the tests failed rather than having errors I'm guessing that's not your issue.

Ping me on IRC and I can help you figure out the problem.

**Comment by paulovmr** [comment]
@mbarkley Thanks for the explanation. 

I had to change a little detail in my implementation, due to a change in the related kie-wb-common PR. That shouldn't break anything, but, in any case, could you please build and run the tests again when you can? Many thanks!

**Pull request merged**
