### PR TITLE
Data sources configurations update

### PR DESCRIPTION
**Pull request by wmedvede**
- adds the by default drivers
    - removes duplicated datasources perspective from extensions menu
    - adds the dashbuilder integration component

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @manstis or @ederign  would you mind review and merge this PR. 
It basically include some configuration tunings for the data sources stuff.

Hello @ederign, @porcelli  Eder, Alexandre, prior to leave today I could see that this tunings were missing in the livespark showcase. Please include them in your local sources.

**Comment by wmedvede** [comment]
Jenkins please retest this.

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Comment by mbarkley** [comment]
+1

/cc @manstis

**Pull request merged**
