### PR TITLE
UF-305 Update reference to PatternFlyTheme module

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Depends on https://github.com/uberfire/uberfire/pull/442

**Comment by cristianonicolai** [comment]
Looks like jenkins is using the maven Uberfire snapshot dependency instead of building the PR branch with same name.

**Comment by psiroky** [comment]
@cristianonicolai correct and expected. Livespark is not in our "blessed" repository list (https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/blob/master/script/repository-list.txt)

**Comment by csadilek** [comment]
+1

**Pull request merged**
